services:
    '@enhavo/newsletter/stats/StatsApp':
        arguments:
            - 'param:data.resource'
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/app/action/ActionManager'
            - '@enhavo/app/vue/VueRegistry'

    '@enhavo/newsletter/components/stats/IndexComponent.vue':
        static: true

    '@enhavo/newsletter/action/NewsletterSendAction':
        import: NewsletterSendAction
        arguments:
            - '@enhavo/app/form/Form'
            - '@enhavo/core/Translator'
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/core/Router'
            - '@enhavo/app/flash-message/FlashMessenger'
        tags:
            - { name: 'enhavo_app.action', class: 'NewsletterSendAction' }

    '@enhavo/newsletter/action/NewsletterSendTestAction':
        import: NewsletterSendTestAction
        arguments:
            - '@enhavo/app/flash-message/FlashMessenger'
            - '@enhavo/core/Translator'
            - '@enhavo/app/modal/ModalManager'
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/core/Router'
        tags:
            - { name: 'enhavo_app.action', class: 'NewsletterSendTestAction' }